title: "Yggdrasil: Docs"
yggdrasil: "What miracle is this? This giant tree. It stands ten thousand feet high But doesn't reach the ground. Still it stands. Its roots must hold the sky."
baseurl: /
url: https://tyleretters.github.io/yggdrasil-docs
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
collections_dir: collections
collections:
  - commands
  - glossary
  - interactions