title: "Yggdrasil: Docs"
baseurl: /
url: https://tyleretters.github.io/yggdrasil-docs
permalink: pretty
sort_by: year, month
markdown: kramdown
kramdown:
  parse_block_html: true
collections_dir: collections
collections:
  - commands
  - interactions